name: simwego-api
region: fra
services:
- name: api
  source_dir: /
  github:
    repo: Felicien410/simwego-api
    branch: main
  run_command: npm start
  environment_slug: node-js
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  health_check:
    http_path: /health
  envs:
  - key: NODE_ENV
    value: production
  - key: PORT
    value: "8080"
  - key: DB_HOST
    scope: RUN_TIME
    type: SECRET
  - key: DB_PORT
    value: "25060"
  - key: DB_NAME
    scope: RUN_TIME
    type: SECRET
  - key: DB_USER
    scope: RUN_TIME
    type: SECRET
  - key: DB_PASSWORD
    scope: RUN_TIME
    type: SECRET
  - key: DB_ENCRYPTION_KEY
    scope: RUN_TIME
    type: SECRET
  - key: MONTY_API_BASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: CLIENT1_MONTY_USERNAME
    scope: RUN_TIME
    type: SECRET
  - key: CLIENT1_MONTY_PASSWORD
    scope: RUN_TIME
    type: SECRET
  - key: CLIENT2_MONTY_USERNAME
    scope: RUN_TIME
    type: SECRET
  - key: CLIENT2_MONTY_PASSWORD
    scope: RUN_TIME
    type: SECRET
  - key: CLIENT_TEST_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: CLIENT_REAL_API_KEY
    scope: RUN_TIME
    type: SECRET
  - key: ADMIN_JWT_SECRET
    scope: RUN_TIME
    type: SECRET
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET

databases:
- name: simwego-db
  engine: PG
  version: "15"
  size: db-s-1vcpu-1gb